services:
  db:
    image: mysql:latest
    container_name: todo_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}